/* autogenerated - do not edit */
#ifndef VOXDEFS_H
#define VOXDEFS_H
#define DISABLE_MELODY
#define NUMSTEP 1
#define vword_xmins 110
#define vword_xminp 110
#define vword_xi 111
#define vword_xinch 112
#define vword_xmm 113
#define vword_xmil 114
#define vword_xvox 115
#define vword_xspeeds 116
#define vword_xspeedp 116
#define vword_xvtyps 117
#define vword_xvtypp 117
#define vword_xvoff 118
#define vword_xsstil 119
#define vword_xschan 120
#define vword_xsrequ 121
#define vword_xnosig 122
#define vword_xbatts 123
#define vword_xbattp 123
#define vword_xblu 124
#define vword_xperc 125
#define vword_xmelof 126
#define vword_xmelon 127
#define vword_xmilsof 128
#define vword_xmilson 129
#define vword_xoverof 130
#define vword_xoveron 131
#define vword_xcharge 132
#define vword_xstored 133
#define vword_xcancel 134
#define vword_xvol0 135
#define vword_xvol1 136
#define vword_xvol2 137
#define vword_100 100
#define vword_extras 109
#define FULL_100 1
#define vword_xunds vword_extras
#define vword_nonum 110
#define VOICE_COUNT 1
#endif
