/* autogenerated - do not edit */
#ifndef VOXDEFS_H
#define VOXDEFS_H
#define DISABLE_MELODY
#define NUMSTEP 1
#define vword_xmins 109
#define vword_xminp 109
#define vword_xi 110
#define vword_xinch 111
#define vword_xmm 112
#define vword_xmil 113
#define vword_xvox 114
#define vword_xspeeds 115
#define vword_xspeedp 115
#define vword_xvtyps 116
#define vword_xvtypp 116
#define vword_xvoff 117
#define vword_xsstil 118
#define vword_xschan 119
#define vword_xsrequ 120
#define vword_xnosig 121
#define vword_xbatts 122
#define vword_xbattp 122
#define vword_xblu 123
#define vword_xperc 124
#define vword_xmelof 125
#define vword_xmelon 126
#define vword_xmilsof 127
#define vword_xmilson 128
#define vword_xoverof 129
#define vword_xoveron 130
#define vword_xcharge 131
#define vword_xstored 132
#define vword_xcancel 133
#define vword_xvol0 134
#define vword_xvol1 135
#define vword_xvol2 136
#define vword_100 100
#define vword_extras 109
#define FULL_100 1
#define vword_nonum 109
#define VOICE_COUNT 2
#endif
